"""Binary PLY writer for coloured point clouds.

Written by hand rather than pulled from a library: the format is 30 lines of
code, and it keeps point-cloud export working with no optional dependencies.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

_HEADER = """ply
format binary_little_endian 1.0
comment generated by roomviz
element vertex {count}
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
end_header
"""

_VERTEX_DTYPE = np.dtype(
    [
        ("x", "<f4"),
        ("y", "<f4"),
        ("z", "<f4"),
        ("red", "u1"),
        ("green", "u1"),
        ("blue", "u1"),
    ]
)


def write_ply(path: str | Path, points: np.ndarray, colors: np.ndarray | None = None) -> Path:
    """Write an ``(N, 3)`` point cloud with optional ``(N, 3)`` uint8 colours."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    points = np.asarray(points, dtype=np.float32).reshape(-1, 3)
    if colors is None:
        colors = np.full((points.shape[0], 3), 200, np.uint8)
    colors = np.asarray(colors, dtype=np.uint8).reshape(-1, 3)
    if colors.shape[0] != points.shape[0]:
        raise ValueError(
            f"colour count {colors.shape[0]} does not match point count {points.shape[0]}"
        )

    records = np.empty(points.shape[0], dtype=_VERTEX_DTYPE)
    records["x"], records["y"], records["z"] = points[:, 0], points[:, 1], points[:, 2]
    records["red"], records["green"], records["blue"] = (
        colors[:, 0],
        colors[:, 1],
        colors[:, 2],
    )

    with open(path, "wb") as fh:
        fh.write(_HEADER.format(count=points.shape[0]).encode("ascii"))
        fh.write(records.tobytes())
    return path
