"""End-to-end pipeline: media in, 3D scene out."""

from __future__ import annotations

import logging
import re
import time
from dataclasses import dataclass
from pathlib import Path

from .config import PipelineConfig
from .export.gltf import safe_label, write_glb
from .export.ply import write_ply
from .export.scene_json import write_scene_json
from .export.viewer import write_viewer
from .fusion.odometry import estimate_trajectory
from .fusion.scene_fusion import fuse
from .geometry.camera import resolve_intrinsics
from .media.loader import load_frames
from .perception.base import build_depth_backend, build_segmentation_backend
from .types import Observation, Scene

log = logging.getLogger(__name__)


_OBJECT_CLOUD_RE = re.compile(r"^\d{3}_.*\.ply$")


def _clear_previous_object_clouds(objects_dir: Path) -> None:
    """Remove object clouds written by an earlier run, and nothing else.

    Deleting everything matching ``*.ply`` is destructive in ways a user will
    not forgive: it follows a symlinked ``objects/`` straight into whatever it
    points at, and it fires even when the current run reconstructed nothing, so
    a failed run wipes the previous good output.  Only names this exporter
    produces are removed, only from a real directory, and only when it is not a
    symlink.
    """
    if not objects_dir.exists():
        return
    if objects_dir.is_symlink() or not objects_dir.is_dir():
        log.warning(
            "%s is not a plain directory; leaving its contents alone", objects_dir
        )
        return
    for entry in objects_dir.iterdir():
        if entry.is_file() and not entry.is_symlink() and _OBJECT_CLOUD_RE.match(entry.name):
            entry.unlink()


def _remove_stale(path: Path, will_be_written: bool) -> None:
    """Delete an output this run is not going to regenerate."""
    if will_be_written or not path.exists():
        return
    if path.is_symlink() or not path.is_file():
        log.warning("%s is not a plain file; leaving it alone", path)
        return
    log.info("removing stale %s (not regenerated by this run)", path.name)
    path.unlink()


def object_cloud_name(inst) -> str:
    """Filename for an object's PLY.

    Uses the same sanitiser as the glTF node names so that `scene.json` can
    reference both, and a checkpoint with unusual class names cannot make the
    two disagree.
    """
    return f"{inst.instance_id:03d}_{safe_label(inst.label)}.ply"


@dataclass
class PipelineResult:
    scene: Scene
    output_dir: Path
    files: dict[str, Path]
    elapsed: float


def reconstruct(
    input_path: str | Path, cfg: PipelineConfig | None = None
) -> tuple[Scene, list[Observation]]:
    """Run perception + fusion and return the reconstructed scene."""
    cfg = cfg or PipelineConfig()
    cfg.validate()
    started = time.time()

    frames = load_frames(input_path, cfg)
    intr = resolve_intrinsics(
        cfg,
        frames[0].width,
        frames[0].height,
        # Any frame carrying a source file can supply EXIF, not just a lone
        # image.  A folder of phone photos is the case that matters: every shot
        # has a focal length recorded, and gating this on `len(frames) == 1`
        # threw all of it away and fell back to a guessed field of view - which
        # then silently scales every dimension in the output.  Frames from a
        # video name the video file, where there is no EXIF to find, so this
        # simply falls through to the assumed default as before.
        source_path=frames[0].source,
        original_size=frames[0].original_size,
    )
    log.info(
        "intrinsics: fx=%.1f fy=%.1f cx=%.1f cy=%.1f", intr.fx, intr.fy, intr.cx, intr.cy
    )

    depth_backend = build_depth_backend(cfg)
    seg_backend = build_segmentation_backend(cfg)

    depths = []
    segmentations = []
    for frame in frames:
        t0 = time.time()
        depths.append(depth_backend.predict(frame))
        segmentations.append(seg_backend.predict(frame))
        log.info(
            "frame %d/%d perceived in %.2fs",
            frame.index + 1,
            len(frames),
            time.time() - t0,
        )

    poses = estimate_trajectory(frames, depths, intr, cfg)

    observations = [
        Observation(
            frame=frame,
            depth=depth,
            segmentation=segmentation,
            intrinsics=intr,
            pose=pose,
        )
        for frame, depth, segmentation, pose in zip(
            frames, depths, segmentations, poses, strict=True
        )
    ]

    scene = fuse(observations, cfg)
    scene.meta["elapsed_seconds"] = round(time.time() - started, 2)
    scene.meta["input"] = str(input_path)
    return scene, observations


def export_scene(
    scene: Scene, output_dir: str | Path, cfg: PipelineConfig | None = None
) -> dict[str, Path]:
    """Write every configured output format into ``output_dir``."""
    cfg = cfg or PipelineConfig()
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    files: dict[str, Path] = {}

    files["scene_json"] = write_scene_json(output_dir / "scene.json", scene, cfg)

    # An artefact that is not being rewritten must not be left behind: the
    # viewer takes its geometry from scene.glb and its labels from scene.json,
    # so a stale GLB beside a fresh JSON renders the previous reconstruction
    # annotated with the current one's numbers.
    _remove_stale(output_dir / "scene.ply", cfg.export_ply)
    _remove_stale(output_dir / "scene.glb", cfg.export_glb)

    if cfg.export_ply:
        files["cloud_ply"] = write_ply(
            output_dir / "scene.ply", scene.points, scene.colors
        )

    # Clear previous object clouds whether or not new ones are being written:
    # leaving them behind next to a fresh scene.json means anything globbing
    # `objects/*.ply` picks up objects from a different reconstruction.
    objects_dir = output_dir / "objects"
    _clear_previous_object_clouds(objects_dir)

    if cfg.export_objects:
        for inst in scene.objects:
            files[f"object_{inst.instance_id}"] = write_ply(
                objects_dir / object_cloud_name(inst),
                inst.points,
                inst.colors,
            )
        if scene.objects:
            log.info("wrote %d object clouds to %s", len(scene.objects), objects_dir)

    if cfg.export_glb:
        files["scene_glb"] = write_glb(output_dir / "scene.glb", scene)

    if cfg.export_viewer:
        files["viewer"] = write_viewer(output_dir)

    return files


def run(
    input_path: str | Path,
    output_dir: str | Path,
    cfg: PipelineConfig | None = None,
) -> PipelineResult:
    """Reconstruct ``input_path`` and write the results to ``output_dir``."""
    cfg = cfg or PipelineConfig()
    started = time.time()
    scene, _ = reconstruct(input_path, cfg)
    files = export_scene(scene, output_dir, cfg)
    elapsed = time.time() - started
    log.info("done in %.1fs -> %s", elapsed, output_dir)
    return PipelineResult(
        scene=scene, output_dir=Path(output_dir), files=files, elapsed=elapsed
    )
